// <auto-generated />
namespace ProjetoPadawanTCC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create04));
        
        string IMigrationMetadata.Id
        {
            get { return "201908281654297_create04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
